version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres3
    restart: always
    environment:
      POSTGRES_DB: attendance_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5065:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./Backend
    container_name: Backend3
    restart: always
    ports:
      - "3065:3065"
    environment:
      PORT: 3065
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: attendance_system
    depends_on:
      - postgres

  frontend:
    build:
      context: ./Frontend
    container_name: Frontend3
    restart: always
    ports:
      - "8102:80"
    depends_on:
      - backend

  hr:
    build:
      context: ./HR
    container_name: HR3
    restart: always
    ports:
      - "8103:80"
    depends_on:
      - backend

volumes:
  pgdata:

